# Generated by Django 6.0.5 on 2026-06-04 10:05

import cloudinary.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_repo', '0002_accessgrant_created_at_user_verified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='full_pdf_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_document_url',
        ),
        migrations.AddField(
            model_name='publication',
            name='full_pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='publications/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
