# Generated by Django 6.0.6 on 2026-06-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_repo', '0004_user_email_verification_token_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(blank=True, help_text='The date this research was published or presented', null=True),
        ),
    ]
